server:
  port: 8080
  servlet:
    context-path: /api

inputFile: /input/player.csv

#H2 Database properties
spring:
  datasource:
    url: jdbc:h2:file:./data/playerdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update

  #Disable batch job's auto start
  batch:
    job:
      enabled: false

  #To always initialize the datasource
    jdbc:
      initialize-schema: always

executor-corePoolSize: 50
executor-maxPoolSize: 100
